services:
  db:
    image: "neo4j:latest"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
